### ISSUE TITLE
files not included

### ISSUE THREAD

**Issue by tuffer020** [Veleslavia/EUSIPCO2017#1]
I could not find where you have the following files:

IRMAS_TRAIN_FEATURE_BASEPATH
IRMAS_TEST_FEATURE_BASEPATH 

I downloaded the dataset and am trying to run the evaluation.py.

Was this intentional?

**Comment by Veleslavia** [comment]
Hi!

Yes, you need to compute features (log-mel spectrograms) for the test part of the dataset. Please, use the preprocessing.py for it. 

You need to create a folder $IRMAS_HOME_DIRECTORY/IRMAS-TestingData-Features/model_name, where model_name is referenced to one of the model filenames in ./experiments/models folder. 

python preprocessing.py -m model_name

**Comment by Veleslavia** [comment]
I forgot to mention, that you also need to create a folder for the training split because preprocessing preprocess them all together.
And, just in case, this code is not ported to keras2, please, use keras<2.0.

**Comment by tuffer020** [comment]
Thank you for your quick reply!
Your comment seems to have done the trick for this particular issue. "singlelayer' is currently running on my machine. I'll make sure to change the keras version. I'll mark this as closed since this issue seems to have been resolved!
